inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'db/**/*'
    - config/**/*
    - bin/**/*
    - lib/**/*
  NewCops: enable  
  
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  Max: 150